### PR TITLE
Move theme files to CDN

### PR DESCRIPTION
**Pull request by MebinAbraham**
### Motivation and Context
Theme files doesn't need to live in the repo, hence it is now called from a CDN.

### What has changed
Removed theme css/js.
Have also added [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to external scripts.

### How to test?
- Look and feel of the app should be unchanged.

Make sure to run `yarn compile` before testing.

### CODE REVIEW

**Comment by MebinAbraham** [comment]
[Move theme CSS to CDN](https://trello.com/c/K47eehaw/49-move-theme-css-to-cdn)

**Review by ryangrundy7 — CHANGES_REQUESTED** [review]
Dashboard works fine but the styling of it is off. The font seems to have gotten bigger

**Comment by MebinAbraham** [comment]
Font issue addressed.

**Review by ryangrundy7 — APPROVED** [review]

**Review by AdamHawtin — APPROVED** [review]

**Review by AdamHawtin — CHANGES_REQUESTED** [review]
The error page styling has changed, the error message is no longer vertically centred

**Comment by MebinAbraham** [comment]
Sorted.

**Review by AdamHawtin — APPROVED** [review]

**Pull request merged**
