### PR TITLE
update certifi

### PR DESCRIPTION
**Pull request by anwilkie**
# What and why?
Updating certifi to resolve dependabot alert

# How to test?
Deploy and make sure service/acceptance tests work.

# Jira
[Card](https://jira.ons.gov.uk/browse/RAS-852)

### CODE REVIEW

**Review by LJBabbage — DISMISSED** [review]
You need to resolve the issue with the yarn lock. Delete it and run yarn install --check-files

**Review by SteveScorfield — APPROVED** [review]
Looks good

**Pull request merged**
